"""Hybrid functional-transition solver for ARC."""

from .control import (
    ActionResult,
    Blackboard,
    BudgetLedger,
    BudgetVector,
    CoverageAwareResidualPolicy,
    ControlAction,
    DeterministicRandomPolicy,
    FixedSchedulePolicy,
    FrozenActionBatch,
    FrozenCandidatePoolProvider,
    RoundRobinPolicy,
    ResidualActionCompiler,
    ResidualCompilerConfig,
    ResidualFirstPolicy,
    ResidualSignal,
    StaticRoutePolicy,
)
from .online import OnlineControlConfig, OnlineFunctionalRouterSolver, OnlineSolveReport
from .deliberation import DeliberationSketch, StructuredDeliberationPolicy
from .metareasoning import (
    NativeBudgetLedger,
    NativeCostContract,
    NativeCostReservation,
    NativeCostVector,
    conditional_mutual_information,
)
from .control_evaluation import (
    AggregateControlMetrics,
    TaskControlMetrics,
    aggregate_control_metrics,
    evaluate_online_report_with_oracle,
)
from .orchestrator import FunctionalRouterConfig, FunctionalRouterSolver, SolveReport
from .providers import (
    CodeModelProvider,
    DiffLogicHardProvider,
    DslProgramProvider,
    MaskedDiffusionProvider,
    OptionalCallbackProvider,
    SparseCAProvider,
)
from .scene_dsl import SceneProgramProvider, SceneRule, execute_scene_rule
from .object_code import (
    D4LabelCompletionProgram,
    FailureCertificate,
    ObjectCodeProvider,
    ObjectCodeResidualCompiler,
    ObjectCodeSynthesisResult,
    RoleStampProgram,
    diagnose_object_code_failure,
    enumerate_object_code_programs,
    execute_object_code_program,
    make_object_code_hypothesis,
    object_code_program_from_json,
    synthesize_object_code_programs,
    typed_repair_frontier,
)
from .repair import generate_repairs, global_color_map_repair, local_transition_repair
from .router import (
    RouteAssignment,
    RouteDecision,
    TaskFeatures,
    extract_task_features,
    route_task,
)
from .types import (
    CandidateEvaluation,
    CandidateHypothesis,
    CandidateProvider,
    ProviderResult,
    RepairReceipt,
)
from .verification import evaluate_hypotheses, evaluate_hypothesis, rank_verified

__all__ = [
    "ActionResult",
    "AggregateControlMetrics",
    "Blackboard",
    "BudgetLedger",
    "BudgetVector",
    "CandidateEvaluation",
    "CandidateHypothesis",
    "CandidateProvider",
    "CodeModelProvider",
    "CoverageAwareResidualPolicy",
    "DiffLogicHardProvider",
    "D4LabelCompletionProgram",
    "DslProgramProvider",
    "ControlAction",
    "DeterministicRandomPolicy",
    "DeliberationSketch",
    "FixedSchedulePolicy",
    "FailureCertificate",
    "FunctionalRouterConfig",
    "FunctionalRouterSolver",
    "FrozenActionBatch",
    "FrozenCandidatePoolProvider",
    "MaskedDiffusionProvider",
    "NativeBudgetLedger",
    "NativeCostContract",
    "NativeCostReservation",
    "NativeCostVector",
    "OnlineControlConfig",
    "OnlineFunctionalRouterSolver",
    "OnlineSolveReport",
    "ObjectCodeProvider",
    "ObjectCodeResidualCompiler",
    "ObjectCodeSynthesisResult",
    "OptionalCallbackProvider",
    "ProviderResult",
    "RepairReceipt",
    "RouteAssignment",
    "RouteDecision",
    "ResidualActionCompiler",
    "ResidualCompilerConfig",
    "ResidualFirstPolicy",
    "ResidualSignal",
    "RoleStampProgram",
    "RoundRobinPolicy",
    "SceneProgramProvider",
    "SceneRule",
    "SolveReport",
    "SparseCAProvider",
    "StaticRoutePolicy",
    "StructuredDeliberationPolicy",
    "conditional_mutual_information",
    "diagnose_object_code_failure",
    "enumerate_object_code_programs",
    "TaskFeatures",
    "TaskControlMetrics",
    "aggregate_control_metrics",
    "evaluate_hypotheses",
    "evaluate_hypothesis",
    "evaluate_online_report_with_oracle",
    "execute_scene_rule",
    "execute_object_code_program",
    "extract_task_features",
    "generate_repairs",
    "global_color_map_repair",
    "local_transition_repair",
    "make_object_code_hypothesis",
    "object_code_program_from_json",
    "rank_verified",
    "route_task",
    "synthesize_object_code_programs",
    "typed_repair_frontier",
]
